# Generated by Django 3.1 on 2020-08-16 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200817_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='Item_text',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_number',
            new_name='Order_text',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
